### ISSUE TITLE
Identify requirements for moving to a dockerized solution

### ISSUE THREAD

**Issue by PadsterH2012** [PadsterH2012/extractor#31]
Create a plan to move this to work in a docker container

it should have the ability in the ui to connect to mongodb and chromadb

we will move the dockerised result into a new repository moving forward.

rpger-content-extractor

---

### Overview
Implement two deployment options to provide maximum flexibility:
1. **Full Container Stack** - Self-contained with all databases
2. **External Databases** - App container connecting to external/managed databases

#### Setup Option 1: Full Container Stack
```
┌─────────────────────────────────────┐
│           Docker Compose            │
├─────────────────────────────────────┤
│ ┌─────────┐ ┌─────────┐ ┌─────────┐ │
│ │   App   │ │ MongoDB │ │ChromaDB │ │
│ │Container│ │Container│ │Container│ │
│ └─────────┘ └─────────┘ └─────────┘ │
│ ┌─────────────────────────────────┐ │
│ │         Nginx Proxy             │ │
│ └─────────────────────────────────┘ │
└─────────────────────────────────────┘
```

#### Setup Option 2: App Container + External DBs
```
┌─────────────────┐    ┌─────────────────┐
│   App Container │────│  External       │
│                 │    │  MongoDB Atlas  │
│                 │    │  (or self-host) │
│                 │────┼─────────────────┤
│                 │    │  External       │
│                 │    │  ChromaDB       │
│                 │    │  (or Pinecone)  │
└─────────────────┘    └─────────────────┘
```

#### 1. Multiple Docker Compose Files (Recommended)

**docker-compose.yml** (Base services)
```yaml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    # Common app config
```

**docker-compose.containers.yml** (DB containers)
```yaml
version: '3.8'
services:
  app:
    depends_on:
      - mongodb
      - chromadb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - CHROMADB_URL=http://chromadb:8000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/data

volumes:
  mongodb_data:
  chromadb_data:
```

**docker-compose.external.yml** (External DB config)
```yaml
version: '3.8'
services:
  app:
    environment:
      - MONGODB_URL=${EXTERNAL_MONGODB_URL}
      - CHROMADB_URL=${EXTERNAL_CHROMADB_URL}
```

#### 2. Startup Scripts

**start-containers.sh**
```bash
#!/bin/bash
echo "Starting with container databases..."
docker-compose -f docker-compose.yml -f docker-compose.containers.yml up -d
```

**start-external.sh**
```bash
#!/bin/bash
echo "Starting with external databases..."
docker-compose -f docker-compose.yml -f docker-compose.external.yml up -d
```

#### 3. UI Configuration Panel Enhancements
- **Setup Mode Selector**: Radio buttons for "Container Stack" vs "External Databases"
- **Dynamic Connection Fields**: Show/hide based on selected mode
- **Connection Testing**: Built-in connectivity tests for external DBs
- **Migration Tools**: Help users migrate between setups

#### 4. Environment Templates

```bash
# .env.containers (Option 1)
SETUP_MODE=containers
MONGODB_URL=mongodb://localhost:27017
CHROMADB_URL=http://localhost:8000

# .env.external (Option 2)  
SETUP_MODE=external
MONGODB_URL=mongodb+srv://user:pass@cluster.mongodb.net/
CHROMADB_URL=https://your-chromadb-instance.com
```

#### Container Stack (Option 1)
- ✅ Zero external dependencies
- ✅ Consistent development environment
- ✅ Easy local testing
- ✅ Complete data control
- ❌ Higher resource usage (~1.5GB total)
- ❌ More complex backup/scaling

#### External Databases (Option 2)
- ✅ Managed database services (Atlas, etc.)
- ✅ Better scalability
- ✅ Professional backup/monitoring
- ✅ Lower local resource usage (~200MB)
- ❌ Network dependency
- ❌ Potential costs for managed services

### Resource Efficiency
- **External mode**: Only app container runs (~200MB)
- **Container mode**: App + MongoDB + ChromaDB (~1.5GB total)
- **Images**: DB images only downloaded when first used
- **Build time**: Only app container builds in external mode

### Documentation Structure
```
docs/
├── deployment/
│   ├── container-stack-setup.md
│   ├── external-db-setup.md
│   └── migration-guide.md
└── docker/
    ├── Dockerfile
    ├── docker-compose.yml
    ├── docker-compose.containers.yml
    └── docker-compose.external.yml
```

### Migration to rpger-content-extractor
This dual approach would make the new repository much more versatile:
- Developers could use the full container stack for local development
- Production deployments could leverage managed database services
- Clean separation of concerns with proper configuration management
- Health checks and monitoring built-in
- Optimized for container deployment patterns
